let employees = [
  { id: 1, name: "Dinesh", gender: "Male", email: "dinesh@ibm.com" },
  { id: 2, name: "Dev", gender: "Male", email: "dev@ibm.com" },
  { id: 3, name: "Jagadish", gender: "Male", email: "jagadish@ibm.com" },
  { id: 4, name: "Gokul", gender: "Male", email: "gokul@ibm.com" },
  { id: 5, name: "Kanishka", gender: "Female", email: "kanishka@ibm.com" },
  { id: 6, name: "Narasimha", gender: "Female", email: "mlamar5@illinois.edu" },
  { id: 7, name: "Tessa", gender: "Female", email: "tdrohan6@nba.com" },
  { id: 8, name: "Joelly", gender: "Female", email: "jfreckleton7@blog.com" },
  {
    id: 9,
    name: "Carrie",
    gender: "Female",
    email: "ccowperthwaite8@miibeian.gov.cn",
  },
  {
    id: 10,
    name: "Opaline",
    gender: "Polygender",
    email: "ogiovannilli9@hp.com",
  },
  { id: 11, name: "Coralie", gender: "Female", email: "cgiorgiellia@ca.gov" },
  { id: 12, name: "Kally", gender: "Female", email: "kwhitsunb@icq.com" },
  { id: 13, name: "Abe", gender: "Male", email: "aconeybearec@cloudflare.com" },
  {
    id: 14,
    name: "Hamilton",
    gender: "Polygender",
    email: "hfroggattd@ihg.com",
  },
  { id: 15, name: "Jeremias", gender: "Male", email: "jchamberse@xing.com" },
  { id: 16, name: "Orin", gender: "Male", email: "ocazinf@google.co.jp" },
  { id: 17, name: "Errick", gender: "Male", email: "eottleyg@wikispaces.com" },
  {
    id: 18,
    name: "Shaun",
    gender: "Female",
    email: "stownshendh@mapquest.com",
  },
  {
    id: 19,
    name: "Mildrid",
    gender: "Female",
    email: "mvandeveldei@statcounter.com",
  },
  { id: 20, name: "Winnah", gender: "Female", email: "wcamberj@reuters.com" },
  { id: 21, name: "Northrop", gender: "Male", email: "ncarlank@buzzfeed.com" },
  { id: 22, name: "Nikos", gender: "Male", email: "nwollastonl@ustream.tv" },
  { id: 23, name: "Lorenza", gender: "Bigender", email: "liacomim@cnn.com" },
  { id: 24, name: "Kermit", gender: "Male", email: "kbernardinn@tmall.com" },
  { id: 25, name: "Emanuel", gender: "Male", email: "edooneo@zimbio.com" },
  {
    id: 26,
    name: "Kirsti",
    gender: "Polygender",
    email: "kbrashierp@sogou.com",
  },
  {
    id: 27,
    name: "Dillie",
    gender: "Male",
    email: "dbabalolaq@wunderground.com",
  },
  { id: 28, name: "Titos", gender: "Male", email: "tdraycottr@amazon.co.uk" },
  { id: 29, name: "Vannie", gender: "Female", email: "vtotts@tamu.edu" },
  {
    id: 30,
    name: "Willey",
    gender: "Agender",
    email: "wmacilwrickt@vimeo.com",
  },
  {
    id: 31,
    name: "Juditha",
    gender: "Female",
    email: "jdeeproseu@arstechnica.com",
  },
  { id: 32, name: "Ike", gender: "Male", email: "idavisv@dagondesign.com" },
  {
    id: 33,
    name: "Rosamond",
    gender: "Female",
    email: "rmccuthaisw@comsenz.com",
  },
  { id: 34, name: "Dolph", gender: "Male", email: "dlandegx@last.fm" },
  { id: 35, name: "Zonda", gender: "Female", email: "zdeverelly@4shared.com" },
  { id: 36, name: "Swen", gender: "Polygender", email: "strundellz@ftc.gov" },
  {
    id: 37,
    name: "Jorge",
    gender: "Male",
    email: "jmaccrackan10@slashdot.org",
  },
  {
    id: 38,
    name: "Marylinda",
    gender: "Female",
    email: "monslow11@geocities.com",
  },
  {
    id: 39,
    name: "Bree",
    gender: "Female",
    email: "bassinder12@ycombinator.com",
  },
  { id: 40, name: "Issiah", gender: "Male", email: "igrimmert13@mysql.com" },
  {
    id: 41,
    name: "Britney",
    gender: "Female",
    email: "bfellgett14@acquirethisname.com",
  },
  {
    id: 42,
    name: "Madeleine",
    gender: "Female",
    email: "mgristhwaite15@pbs.org",
  },
  { id: 43, name: "Neely", gender: "Female", email: "nnairns16@springer.com" },
  { id: 44, name: "Welby", gender: "Male", email: "wgarden17@upenn.edu" },
  { id: 45, name: "Lotti", gender: "Female", email: "lmushart18@tiny.cc" },
  { id: 46, name: "Onfre", gender: "Male", email: "ogloster19@youtube.com" },
  {
    id: 47,
    name: "Chrotoem",
    gender: "Male",
    email: "cgerge1a@networkadvertising.org",
  },
  { id: 48, name: "Tana", gender: "Female", email: "tthrelfall1b@tmall.com" },
  {
    id: 49,
    name: "Cissy",
    gender: "Female",
    email: "cbranston1c@omniture.com",
  },
  {
    id: 50,
    name: "Lanny",
    gender: "Female",
    email: "lmaffioletti1d@t-online.de",
  },
  { id: 51, name: "Jobye", gender: "Female", email: "jortell1e@flavors.me" },
  {
    id: 52,
    name: "Cacilia",
    gender: "Female",
    email: "cmaureen1f@myspace.com",
  },
  { id: 53, name: "Jim", gender: "Male", email: "jtrippitt1g@yellowbook.com" },
  {
    id: 54,
    name: "Angelle",
    gender: "Female",
    email: "aramstead1h@merriam-webster.com",
  },
  { id: 55, name: "Rosene", gender: "Female", email: "rroake1i@dot.gov" },
  { id: 56, name: "Georgeta", gender: "Female", email: "gmegahey1j@ocn.ne.jp" },
  {
    id: 57,
    name: "Gabriela",
    gender: "Female",
    email: "glambarth1k@google.cn",
  },
  {
    id: 58,
    name: "Lyndsay",
    gender: "Female",
    email: "ltackell1l@printfriendly.com",
  },
  { id: 59, name: "Elladine", gender: "Female", email: "ebrunn1m@boston.com" },
  { id: 60, name: "Gerick", gender: "Male", email: "gkeirle1n@deviantart.com" },
  { id: 61, name: "Erwin", gender: "Male", email: "eorrock1o@cbslocal.com" },
  {
    id: 62,
    name: "Marylin",
    gender: "Agender",
    email: "mstanworth1p@globo.com",
  },
  { id: 63, name: "Jessey", gender: "Male", email: "jbaford1q@tinyurl.com" },
  {
    id: 64,
    name: "Marianna",
    gender: "Female",
    email: "mlightfoot1r@elpais.com",
  },
  { id: 65, name: "Onfre", gender: "Male", email: "ogoburn1s@cbslocal.com" },
  { id: 66, name: "Erhart", gender: "Male", email: "einmett1t@google.ru" },
  { id: 67, name: "Pietro", gender: "Male", email: "pboole1u@over-blog.com" },
  { id: 68, name: "Hal", gender: "Male", email: "hdeedes1v@gov.uk" },
  { id: 69, name: "Gianni", gender: "Male", email: "gcrissil1w@360.cn" },
  { id: 70, name: "Levin", gender: "Male", email: "ldunkerley1x@fc2.com" },
  {
    id: 71,
    name: "Claudie",
    gender: "Female",
    email: "cfarmiloe1y@google.com.hk",
  },
  { id: 72, name: "Car", gender: "Male", email: "cpetigrew1z@joomla.org" },
  { id: 73, name: "Ulrikaumeko", gender: "Female", email: "ugorch20@360.cn" },
  {
    id: 74,
    name: "Claudio",
    gender: "Male",
    email: "cchazier21@biglobe.ne.jp",
  },
  {
    id: 75,
    name: "Kendal",
    gender: "Male",
    email: "kreveland22@moonfruit.com",
  },
  {
    id: 76,
    name: "Ranice",
    gender: "Female",
    email: "rcull23@theatlantic.com",
  },
  {
    id: 77,
    name: "Cord",
    gender: "Male",
    email: "cseifenmacher24@bloomberg.com",
  },
  {
    id: 78,
    name: "Darren",
    gender: "Male",
    email: "drawcliffe25@theglobeandmail.com",
  },
  { id: 79, name: "Ethel", gender: "Female", email: "erape26@mozilla.org" },
  { id: 80, name: "Dwain", gender: "Male", email: "dgarnham27@jigsy.com" },
  { id: 81, name: "Faith", gender: "Bigender", email: "fvolk28@youtube.com" },
  { id: 82, name: "Ariela", gender: "Female", email: "amacgill29@goo.gl" },
  { id: 83, name: "Wendi", gender: "Female", email: "wbedle2a@auda.org.au" },
  { id: 84, name: "Malva", gender: "Female", email: "meberle2b@wufoo.com" },
  { id: 85, name: "Ave", gender: "Male", email: "aschust2c@last.fm" },
  { id: 86, name: "Palm", gender: "Male", email: "pbayman2d@newyorker.com" },
  { id: 87, name: "Ardine", gender: "Bigender", email: "aedser2e@npr.org" },
  { id: 88, name: "Dante", gender: "Male", email: "dpassfield2f@t-online.de" },
  {
    id: 89,
    name: "Marnia",
    gender: "Female",
    email: "mhartness2g@amazonaws.com",
  },
  { id: 90, name: "Sarette", gender: "Female", email: "ssellar2h@furl.net" },
  {
    id: 91,
    name: "Yvette",
    gender: "Female",
    email: "yzanitti2i@virginia.edu",
  },
  {
    id: 92,
    name: "Nealson",
    gender: "Male",
    email: "nklimontovich2j@ucoz.com",
  },
  { id: 93, name: "Caron", gender: "Female", email: "ccasillas2k@ehow.com" },
  {
    id: 94,
    name: "Dore",
    gender: "Male",
    email: "dfanthome2l@bizjournals.com",
  },
  {
    id: 95,
    name: "Leshia",
    gender: "Female",
    email: "lgilburt2m@omniture.com",
  },
  { id: 96, name: "Lazaro", gender: "Male", email: "lpossel2n@redcross.org" },
  { id: 97, name: "Reagan", gender: "Male", email: "rbrumham2o@tmall.com" },
  { id: 98, name: "Akim", gender: "Male", email: "abloxam2p@gnu.org" },
  { id: 99, name: "Kipp", gender: "Male", email: "kcafe2q@google.com.br" },
  { id: 100, name: "Normy", gender: "Male", email: "nbezzant2r@bandcamp.com" },
];

function displayData() {
  let rows = "";
  let i = 0;
  while (i <= employees.length - 1) {
    rows =
      rows +
      `<tr>
        <td>${employees[i].id}</td>
        <td>${employees[i].name}</td>
        <td>${employees[i].gender}</td>
        <td>${employees[i].email}</td>
        </tr>`;
    i++;
  }
  document.getElementById("tabDat").innerHTML = rows;
}
